"""add property images and video url

Revision ID: 4618a39b3e9f
Revises: e4840a08166c
Create Date: 2026-07-24 13:30:32.528715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4618a39b3e9f'
down_revision = 'e4840a08166c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_images_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_images_property_id'))

    op.drop_table('property_images')
    # ### end Alembic commands ###
