"""add property video table

Revision ID: 8552108206c3
Revises: 4618a39b3e9f
Create Date: 2026-07-25 07:01:35.556438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8552108206c3'
down_revision = '4618a39b3e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_videos_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_videos_property_id'))

    op.drop_table('property_videos')
    # ### end Alembic commands ###
