"""add listing_type to properties

Revision ID: bbb494203b3f
Revises: ebc5c56bb816
Create Date: 2026-08-06 20:22:49.918309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb494203b3f'
down_revision = 'ebc5c56bb816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_type', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('listing_type')

    # ### end Alembic commands ###
