"""add unavailable_dates table

Revision ID: e4840a08166c
Revises: 70287ba6af28
Create Date: 2026-07-24 11:38:38.980470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4840a08166c'
down_revision = '70287ba6af28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unavailable_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('end_date > start_date', name='ck_unavailable_dates_valid'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unavailable_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unavailable_dates_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unavailable_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unavailable_dates_property_id'))

    op.drop_table('unavailable_dates')
    # ### end Alembic commands ###
